baseURL = 'https://irwins.github.io/blog/'
languageCode = 'en-us'
title = 'My digital journey'
theme = "m10c"
paginate = 10
publishDir = "docs"
enableEmoji = true

[taxonomies]
  tag = 'tags'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
author = 'Irwin Strachan'
description = 'A blog about my digital transformation journey to cloud native and beyond.'

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/irwins"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/irwinstrachan"

[[params.social]]
icon = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/irwinstrachan/"

